markdown: kramdown
kramdown:
    toc_levels: 2..5

collections:
    categories:
        output: true
    authors:
        output: true

defaults:
    - scope:
        path: ""
        type: "categories"
      values:
        layout: category
    - scope:
        path: ""
        type: "posts"
      values:
        layout: post
    - scope:
        path: ""
      values:
        layout: default
