markdown: kramdown
kramdown:
    toc_levels: 2..5

defaults:
    - scope:
        path: ""
        type: "posts"
      values:
        layout: post
    - scope:
        path: ""
      values:
        layout: default
